### ISSUE TITLE
Some fun pages

### ISSUE THREAD

**Issue by luisfmsouza** [lnfnunes/404-PageNotFound#26]
Take a look at these fun pages: http://blog.usabilla.com/fantastically-funny-404-pages/

**Comment by lnfnunes** [comment]
Very nice @luisfmsouza !
Let's incorporate those URLs... PR ? 😉

**Comment by lnfnunes** [comment]
To celebrate the Hacktoberfest, everyone is welcome to close this issue with a simple PR =)
Happy Hacktoberfest and happy hacking! 🎉

**Comment by laurenball** [comment]
Hi @lnfnunes! I can open a PR for this :)

**Comment by lnfnunes** [comment]
Solved by PR #28
