### ISSUE TITLE
Remove Udemy.com

### ISSUE THREAD

**Issue by lnfnunes** [lnfnunes/404-PageNotFound#29]
Udemy 404 page is returning error 500 and it's breaking the build on Travis.
- [ ] TODO: remove **Udemy** item from [LIST.md](./LIST.md)

To celebrate the Hacktoberfest, everyone is welcome to close this issue with a simple PR =)
Happy Hacktoberfest and happy hacking! 🎉

**Comment by SioJL13** [comment]
I'll do it

**Comment by lnfnunes** [comment]
Don in PR #31
