### ISSUE TITLE
Fix logo

### ISSUE THREAD

**Issue by lnfnunes** [lnfnunes/404-PageNotFound#30]
Logo in LIST.md is outdated URL causing image not found.
- [x] TODO: change logo <img> path from [LIST.md](./LIST.md) ot be the same as in [README.md](README.md)
- [x] TODO: change _alt_ attribute from both md files above to be "Logo of project Page 404 Not Found"

To celebrate the Hacktoberfest, everyone is welcome to close this issue with a simple PR =)
Happy Hacktoberfest and happy hacking! 🎉

**Comment by raghav15** [comment]
i ll do it :)

**Comment by lnfnunes** [comment]
Closed on PR #33
