### ISSUE TITLE
Add unit-tests for checkorder.js

### ISSUE THREAD

**Issue by lnfnunes** [lnfnunes/404-PageNotFound#58]
## About
_checkorder.js_ is a script that parse the links of a .md file and check if the list is alphabetically sorted!
## Usage
```node checkorder.js LIST.md```

> To celebrate the Hacktoberfest, everyone is welcome to close this issue =)
Happy Hacktoberfest and happy hacking! 🎉

**Comment by dgautsch** [comment]
Do you have a preference in test framework?
