### ISSUE TITLE
Disabling `Update branch` button

### ISSUE THREAD

**Issue by luisfmsouza** [lnfnunes/404-PageNotFound#98]
Think we can disable this `update branch` button (image below) from PR on this repo settings. This button is just adding some noisy to all opened pull requests, because it enforces the branches to be up-to-date with master all the time, and we had to be requesting rebasing/squashes.

Button:
![image](https://user-images.githubusercontent.com/4405147/46960785-a737c080-d075-11e8-9c77-2870e3ddb6d5.png)

Example of the noisy:
![image](https://user-images.githubusercontent.com/4405147/46960848-cfbfba80-d075-11e8-8af5-0f6fb48f0017.png)

Even when we disable the button, Github will guarantee to use integrity of the code. And also, it will tell us when there's a conflict between branches, the we can act directly on it before merge. Otherwise, there's no need to be up-to-date with master all the time.

**Comment by lnfnunes** [comment]
I have a different opinion about this point. I like to enforce branches to be up-to-date with master always, so the _"Update branch"_ button is just a try, exactly, to prevent asking people to do rebasing themselves.

Even though your print is showing a _noisy_, the master timeline is kept untouched and clean
![image](https://user-images.githubusercontent.com/2450417/46985794-95303f00-d0c2-11e8-8ca0-d6a0b23ff956.png)

How to garantee the PR is up-to-date with master and we are not loosing anything? I'm not sure if only in conflicted state this could happen...

**Anyway, I'll change the settings and we can give it a try ✌️**

**Comment by luisfmsouza** [comment]
Let's try it.

**Comment by rsp** [comment]
Sorry for an off-topic question but how have you managed to disable the 'Update branch' button? I was sure that it is impossible to disable it (see [those comments](https://github.com/isaacs/github/issues/1113#issuecomment-442998233)).

**Comment by lnfnunes** [comment]
@rsp we dont't 'disable' the button as you may be thinking, we just remove the check forcing branches to be up-to-date with master. Personaly I preffer to keep this ON, but as @luisfmsouza said, it adds some misunderstanding on novice people and dificult contributions with some kind of 'invisibile contribute wall' rule!

Settings 👇
![image](https://user-images.githubusercontent.com/2450417/53758082-da031980-3e9b-11e9-96e8-a70606925c61.png)

So far, so good! We had no problems without this option 🙂

**Comment by Bubesz** [comment]
> @rsp we don't "disable" the button as you may be thinking, we just remove the check forcing branches to be up-to-date with master. Personally, I prefer to keep this ON, but as @luisfmsouza said, it adds some misunderstanding on novice people and difficult contributions with some kind of _`invisible contribute wall`_ rule!
> 
> Settings 👇
> ![image](https://user-images.githubusercontent.com/2450417/53758082-da031980-3e9b-11e9-96e8-a70606925c61.png)
> 
> So far, so good! We had no problems without this option 🙂

This was extremely valuable information for me! I'm glad you shared it! 👍

I added the "Require status checks to pass before merging" rule with the aforementioned "Require branches to be up to date before merging" rule at the beginning of a testing period. Because of the low intensity of coding (to main branch), we did not come across the "Update Branch" button for days and on one hand, I forgot I added such a rule, and more importantly,

I expected this button to rebase the PR HEAD branch onto the base branch but instead, it creates a merge commit. We use rebase everywhere, so we'd like to avoid merges. This way, we had to manually rebase our branches which was a headache. Currently, the update strategy of the Update Branch button cannot be configured. Actually, there is an issue related to this: https://github.com/isaacs/github/issues/1419

**Comment by SpootyMcSpoot** [comment]
Any update here? I'd like to see the option of enforcing this without the button present. Devs can rebase on their local and push rather than use the button.

**Comment by bgrosse-midokura** [comment]
![image](https://user-images.githubusercontent.com/48123182/128321361-91f4f13f-72de-4548-bb96-21f1029739d0.png)

I can't find this checkbox in Settings?

**Comment by lnfnunes** [comment]
Enabled it!

<img width="419" alt="Screen Shot 2021-08-05 at 22 22 23" src="https://user-images.githubusercontent.com/2450417/128441632-1c5fefe4-d144-4780-9d79-e945c8c8ca44.png">

**Comment by mo-klue** [comment]
https://github.com/motakbiri/UpdateBranchRemover/

**Comment by thiagoszbarros** [comment]
https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-suggestions-to-update-pull-request-branches
